name: windbolt
description: "A group chat Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat/static/Caveat-Medium.ttf
          weight: 300
        - asset: assets/fonts/Caveat/static/Caveat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Caveat/static/Caveat-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Caveat/static/Caveat-Bold.ttf
          weight: 600